name: Docker Build and Push  # Naziv workflow-a (vidljiv u Actions tabu)

on:
  push:
    branches: [ "main" ]      # Pokreće se kada push-uješ na granu main
  pull_request:
    branches: [ "main" ]      # Pokreće se i na pull request ka main grani

jobs:
  build:
    runs-on: ubuntu-latest    # GitHub Actions koristi Ubuntu virtuelnu mašinu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Preuzima tvoj iz repozitorijuma

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'        # Instalira JDK 17 (za Maven build)
          distribution: 'temurin'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build JAR file
        run: ./mvnw clean package -DskipTests   # Pravi JAR (bez testova jer ih nemamo trenutno)

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Uzima korisničko ime iz tajni
          password: ${{ secrets.DOCKER_PASSWORD }}  # Uzima lozinku/token iz tajni

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cardatabase-backend:latest .
        # Gradi Docker image i taguje ga kao 'latest'

      - name: Push Docker image to Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cardatabase-backend:latest
        # Šalje image na Docker Hub (repo će se automatski kreirati ako ne postoji)
